### ISSUE TITLE
Delphi xe2 is not supported

### ISSUE THREAD

**Issue by guoqingaa** [Cooler2/ApusGameEngine#3]
The source code does not support Delphi xe2，Can you support me? Thank you!

**Comment by Cooler2** [comment]
Sorry I can't - I don't have XE2. I can adopt the code for a freely available version of Delphi, i.e. either D2006 (Turbo Delphi Explorer which is free) or Delphi CE. Although old revisions works with D2006, I don't want to support it anymore because it's pretty much different from the recent Delphi versions, mostly because of outdated RTL: there are so many things to do manually which can be done by RTL by both Delphi and FPC. Re-inventing the RTL isn't good for me.

However, If you can point me on particular issues that make the code incompatible with xe2, I'll consider this info and try to avoid them when it's not crucial.
